const dns = require("dns");

dns.setServers(["8.8.8.8", "1.1.1.1"]);

const mongoose = require("mongoose");
require("dotenv").config();

const Place = require("./models/Place");

const places = [
  {
    name: "Dowa Rock Temple",
    location: "Dowa Rock Temple, Badulla Bandarawela Road, Bandarawela, Sri Lanka .",
    district: "Badulla",
    province: "Uva",
    category: "Historical",
    distance: "6.0km from Bandarawela Bus Stop",
    rating: 0,
    reviews: 0,
    phone: "+94 57 222 8630",
    openingDays: "Monday - Sunday",
    openingHours: "06:00 AM - 06:00 PM",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=6.857425909029196,81.02205925881152",
    description:
      "Historic cave temple known for its 38-foot carved Buddha statue and ancient wall paintings.",
    image: "/images/places/dowa-rock-temple.jpg",
    images: [
      "/images/places/dowa-rock-temple.jpg",
      "/images/places/dowa-rock-temple-1.jpg",
      "/images/places/dowa-rock-temple-2.jpg",
      "/images/places/dowa-rock-temple-3.jpg",
      "/images/places/dowa-rock-temple-4.jpg",
      "/images/places/dowa-rock-temple-5.jpg",
      "/images/places/dowa-rock-temple-6.jpg",
      "/images/places/dowa-rock-temple-7.jpg",
      "/images/places/dowa-rock-temple-8.jpg",
    ],
  },
  {
    name: "Lipton's Seat",
    location: "Lipton Seat Road, Dambethenna Estate, Haputale 90160, Sri Lanka.",
    district: "Badulla",
    province: "Uva",
    category: "Sightseeing",
    distance: "27.5km from Bandarawela Bus Stop",
    rating: 0,
    reviews: 0,
    phone: "+94 57 567 0595",
    openingDays: "Monday - Sunday",
    openingHours: "05:30 AM - 05:00 PM",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=6.789520980363356,81.01761188949553",
    description:
      "Famous viewpoint offering panoramic views of tea estates across multiple provinces.",
    image: "/images/places/liptons-seat.jpg",
    images: [
      "/images/places/liptons-seat.jpg",
      "/images/places/liptons-seat-1.jpg",
      "/images/places/liptons-seat-2.jpg",
      "/images/places/liptons-seat-3.jpg",
    ],
  },
  {
    name: "Ravana Fall",
    location: "Ravana Ella, Ella Wellawaya Road, Ella, 90090, Sri Lanka.",
    district: "Badulla",
    province: "Uva",
    category: "Sightseeing / Nature",
    distance: "19.2km from Bandarawela Bus Stop",
    rating: 0,
    reviews: 0,
    phone: "N/A",
    openingDays: "Monday - Sunday",
    openingHours: "Open 24 Hours",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=6.84074,81.05492",
    description:
      "Iconic roadside waterfall associated with the Ramayana legend, located on the way to Ella.",
    image: "/images/places/ravana-fall.jpg",
    images: [
      "/images/places/ravana-fall.jpg",
      "/images/places/ravana-fall-1.jpg",
      "/images/places/ravana-fall-2.jpg",
      "/images/places/ravana-fall-3.jpg",
      "/images/places/ravana-fall-4.jpg",
      "/images/places/ravana-fall-5.jpg",
      "/images/places/ravana-fall-6.jpg",
    ],
  },
  {
    name: "Nine Arches Bridge",
    location: "Demodara, Ella, Sri Lanka.",
    district: "Badulla",
    province: "Uva",
    category: "Monuments / Architecture",
    distance: "15.4km from Bandarawela Bus Stop",
    rating: 0,
    reviews: 0,
    phone: "N/A",
    openingDays: "Monday - Sunday",
    openingHours: "Open 24 Hours",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=6.87676,81.06076",
    description:
      "Famous colonial-era viaduct bridge surrounded by dense jungle and tea plantations.",
    image: "/images/places/nine-arches-bridge.jpg",
    images: [
      "/images/places/nine-arches-bridge.jpg",
      "/images/places/nine-arches-bridge-1.jpg",
      "/images/places/nine-arches-bridge-2.jpg",
      "/images/places/nine-arches-bridge-3.jpg",
      "/images/places/nine-arches-bridge-4.jpg",
    ],
  },
  {
    name: "Ella Rock",
    location: "Ella Rock Hiking Resort, Kithalella, Ella, 90090, Sri Lanka.",
    district: "Badulla",
    province: "Uva",
    category: "Sightseeing / Hiking",
    distance: "13.8km from Bandarawela Bus Stop",
    rating: 0,
    reviews: 0,
    phone: "N/A",
    openingDays: "Monday - Sunday",
    openingHours: "Open 24 Hours",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=6.8538,81.0464",
    description:
      "Popular cliff top viewpoint providing dramatic panoramic vistas of the southern hills.",
    image: "/images/places/ella-rock.jpg",
    images: [
      "/images/places/ella-rock.jpg",
      "/images/places/ella-rock-1.jpg",
      "/images/places/ella-rock-2.jpg",
      "/images/places/ella-rock-3.jpg",
      "/images/places/ella-rock-4.jpg",
      "/images/places/ella-rock-5.jpg",
      "/images/places/ella-rock-6.jpg",
      "/images/places/ella-rock-7.jpg",
    ],
  },
  {
    name: "Little Adam's Peak",
    location: "Little Adam's Peak, Ella-Passara Road, Ella, Uva, Sri Lanka.",
    district: "Badulla",
    province: "Uva",
    category: "Sightseeing / Hiking",
    distance: "15.1km from Bandarawela Bus Stop",
    rating: 0,
    reviews: 0,
    phone: "+94 70 110 0021",
    openingDays: "Monday - Sunday",
    openingHours: "05:00 AM - 06:30 PM",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=6.8625,81.0638",
    description:
      "Easy, family-friendly hiking trail offering sweeping views over the Ella Gap.",
    image: "/images/places/little-adams-peak.jpg",
    images: [
      "/images/places/little-adams-peak.jpg",
      "/images/places/little-adams-peak-1.jpg",
      "/images/places/little-adams-peak-2.jpg",
      "/images/places/little-adams-peak-3.jpg",
      "/images/places/little-adams-peak-4.jpg",
      "/images/places/little-adams-peak-5.jpg",
    ],
  },
  {
    name: "Adisham Bungalow",
    location: "Adisham Bungalow, Adisham Rd, Haputale 90160, Sri Lanka.",
    district: "Badulla",
    province: "Uva",
    category: "Monuments / Historical",
    distance: "12.8km from Bandarawela Bus Stop",
    rating: 0,
    reviews: 0,
    phone: "+94 57 226 8030",
    openingDays: "Weekends & Public Holidays",
    openingHours: "09:00 AM - 04:30 PM",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=6.773086557447562,80.93099045087155",
    description:
      "Colonial Benedictine monastery surrounded by orchards and thick forest reserves.",
    image: "/images/places/adisham-bungalow.jpg",
    images: [
      "/images/places/adisham-bungalow.jpg",
      "/images/places/adisham-bungalow-1.jpg",
      "/images/places/adisham-bungalow-2.jpg",
      "/images/places/adisham-bungalow-3.jpg",
      "/images/places/adisham-bungalow-4.jpg",
    ],
  },
  {
    name: "Rawana Ella Cave",
    location: "Ravana Ella Cave, Ella Wellawaya Road, Ella.",
    district: "Badulla",
    province: "Uva",
    category: "Monuments / Historical",
    distance: "16.5km from Bandarawela Bus Stop",
    rating: 0,
    reviews: 0,
    phone: "+94 71 613 1211",
    openingDays: "Monday - Sunday",
    openingHours: "08:30 AM - 05:30 PM",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=6.864792997229675,81.04863933379441",
    description:
      "Prehistoric archaeological cave site located on a steep cliff near Ella town.",
    image: "/images/places/rawana-ella-cave.jpg",
    images: [
      "/images/places/rawana-ella-cave.jpg",
      "/images/places/rawana-ella-cave-1.jpg",
      "/images/places/rawana-ella-cave-2.jpg",
      "/images/places/rawana-ella-cave-3.jpg",
      "/images/places/rawana-ella-cave-4.jpg",
    ],
  },
  {
    name: "Porowagala Viewpoint",
    location: "Mahaulpatha, Galkanda, Bandarawela, Sri Lanka",
    district: "Badulla",
    province: "Uva",
    category: "Sightseeing",
    distance: "3.5km from Bandarawela Bus Stop",
    rating: 0,
    reviews: 0,
    phone: "055 222 9675",
    openingDays: "Monday - Sunday",
    openingHours: "Open 24 Hours",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=6.830559988080396,81.01268150484262",
    description:
      "Scenic tea estate area offering traditional tea landscape and valley views.",
    image: "/images/places/porowagala-viewpoint.jpg",
    images: [
      "/images/places/porowagala-viewpoint.jpg",
      "/images/places/porowagala-viewpoint-1.jpg",
      "/images/places/porowagala-viewpoint-2.jpg",
      "/images/places/porowagala-viewpoint-3.jpg",
      "/images/places/porowagala-viewpoint-4.jpg",
      "/images/places/porowagala-viewpoint-5.jpg",
      "/images/places/porowagala-viewpoint-6.jpg",
      "/images/places/porowagala-viewpoint-7.jpg",
      "/images/places/porowagala-viewpoint-8.jpg",
      "/images/places/porowagala-viewpoint-9.jpg",
      "/images/places/porowagala-viewpoint-10.jpg",
    ],
  },
  {
    name: "Halpewatte Tea Factory",
    location: "Uva Halpewatte Tea Factory, Badulla Road, Hela Halpe, Ella, Sri Lanka 90090, Sri Lanka.",
    district: "Badulla",
    province: "Uva",
    category: "Educational",
    distance: "18.2km from Bandarawela Bus Stop",
    rating: 0,
    reviews: 0,
    phone: "+94 57 222 8599",
    openingDays: "Monday - Sunday",
    openingHours: "08:00 AM - 04:30 PM",
    googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=6.89035332628612,81.03424924346947",
    description:
      "Popular tea processing tour offering factory walk-throughs and tea tasting experiences.",
    image: "/images/places/halpewatte-tea-factory.jpg",
    images: [
      "/images/places/halpewatte-tea-factory.jpg",
      "/images/places/halpewatte-tea-factory-1.jpg",
      "/images/places/halpewatte-tea-factory-2.jpg",
      "/images/places/halpewatte-tea-factory-3.jpg",
    ],
  },
];

const BusService = require("./models/BusService");

const busServicesData = [
  {
    name: "Colombo ↔ Bandarawela Highway Luxury Coach",
    routeNumber: "Route 99/EX",
    origin: "Colombo Fort / Makumbura",
    destination: "Bandarawela Central",
    via: "Southern Expressway (E02) → Wellawaya → Haputale → Bandarawela",
    busTimes: [
      { time: "05:30 AM", tag: "Morning Express", icon: "🌅" },
      { time: "08:45 AM", tag: "Day Coach", icon: "☀️" },
      { time: "02:50 PM", tag: "Highway Super", icon: "⚡" },
      { time: "04:30 PM", tag: "Evening Intercity", icon: "🌇" },
      { time: "09:30 PM", tag: "Night Luxury Sleeper", icon: "🌙" },
    ],
    phone: "+94 57 222 2281",
    conductorPhone: "+94 77 105 7740",
    hotline: "1955 (NTC Hotline) / +94 11 770 6000",
    fare: "LKR 1,850",
    busType: "AC King Long Super Luxury (Air-Suspension)",
    description: "Fast direct highway coach connecting Western Capital Colombo to Uva hills via Southern Expressway & Haputale gap.",
    image: "/images/Nearby facilities/Colombo Bandarawela Bus.jpg",
    position: [6.82977, 80.98457],
    routeWaypoints: [
      [6.9271, 79.8612],
      [6.8404, 79.9961],
      [6.7410, 81.1010],
      [6.7670, 80.9560],
      [6.82977, 80.98457],
    ],
    rating: 4.8,
    reviews: 620,
    isInternal: false,
  },
  {
    name: "Colombo ↔ Badulla Intercity Express",
    routeNumber: "Route 99",
    origin: "Colombo Bastian Mawatha",
    destination: "Badulla Bus Stand",
    via: "Avissawella → Ratnapura → Balangoda → Beragala → Bandarawela → Badulla",
    busTimes: [
      { time: "04:15 AM", tag: "Early Express", icon: "🌅" },
      { time: "07:00 AM", tag: "Intercity Line", icon: "🚌" },
      { time: "10:30 AM", tag: "Mid-Day Direct", icon: "☀️" },
      { time: "01:15 PM", tag: "Mountain Pass", icon: "⛰️" },
      { time: "06:00 PM", tag: "Evening Express", icon: "🌆" },
      { time: "10:45 PM", tag: "Night Sleeper", icon: "🌙" },
    ],
    phone: "+94 55 222 2235",
    conductorPhone: "+94 76 590 0100",
    hotline: "1955 (NTC Hotline)",
    fare: "LKR 1,450",
    busType: "SLTB Ashok Leyland Intercity (Semi-Luxury)",
    description: "Classic high-frequency mountain express route connecting Western Province directly to Uva Province heartlands.",
    image: "/images/Nearby facilities/Colombo Badulla Intercity Bus.jpg",
    position: [6.9934, 81.0550],
    routeWaypoints: [
      [6.9271, 79.8612],
      [6.9530, 80.2070],
      [6.6828, 80.3992],
      [6.6500, 80.7000],
      [6.82977, 80.98457],
      [6.9934, 81.0550],
    ],
    rating: 4.6,
    reviews: 840,
    isInternal: false,
  },
  {
    name: "Colombo ↔ Ella Direct Tourist Express",
    routeNumber: "Route 99/EX-Ella",
    origin: "Colombo Fort Terminal",
    destination: "Ella Main Street",
    via: "Southern Highway → Wellawaya → Ravana Falls → Ella Town",
    busTimes: [
      { time: "06:00 AM", tag: "Morning Tourist Express", icon: "🌅" },
      { time: "09:30 AM", tag: "Scenic Highway Coach", icon: "☀️" },
      { time: "01:30 PM", tag: "Afternoon Express", icon: "🚌" },
      { time: "11:15 PM", tag: "Overnight Tourist Sleeper", icon: "🌙" },
    ],
    phone: "+94 74 200 0490",
    conductorPhone: "+94 76 138 2300",
    hotline: "+94 11 258 1112 (SLTB Colombo)",
    fare: "LKR 2,100",
    busType: "AC Super Luxury Air-Suspension Coach",
    description: "Dedicated tourist luxury express connecting Colombo directly to Ella town and Ravana waterfalls.",
    image: "/images/Nearby facilities/Colombo Ella Express Bus.jpg",
    position: [6.8667, 81.0466],
    routeWaypoints: [
      [6.9271, 79.8612],
      [6.8404, 79.9961],
      [6.7410, 81.1010],
      [6.866848, 81.044513],
      [6.8667, 81.0466],
    ],
    rating: 4.9,
    reviews: 490,
    isInternal: false,
  },
  {
    name: "Kandy ↔ Badulla / Ella Scenic Intercity",
    routeNumber: "Route 10",
    origin: "Kandy Goods Shed",
    destination: "Badulla & Ella Town",
    via: "Peradeniya → Nuwara Eliya → Welimada → Bandarawela → Ella → Badulla",
    busTimes: [
      { time: "05:00 AM", tag: "Hill Pass Dawn Express", icon: "🌅" },
      { time: "07:30 AM", tag: "Nuwara Eliya Line", icon: "☕" },
      { time: "10:15 AM", tag: "Tea Country Scenic", icon: "⛰️" },
      { time: "01:00 PM", tag: "Afternoon Pass", icon: "☀️" },
      { time: "04:30 PM", tag: "Evening Intercity", icon: "🌆" },
    ],
    phone: "+94 81 222 2235",
    conductorPhone: "+94 57 222 2281",
    hotline: "+94 81 222 2235 (Kandy Depot)",
    fare: "LKR 1,150",
    busType: "SLTB Mountain Line Intercity",
    description: "Breathtaking mountain pass bus connecting Central Hill Capital Kandy to Uva tourist destinations.",
    image: "/images/Nearby facilities/Kandy Badulla Intercity Bus.jpg",
    position: [6.9934, 81.0550],
    routeWaypoints: [
      [7.2906, 80.6337],
      [6.9497, 80.7891],
      [6.9015, 80.9520],
      [6.82977, 80.98457],
      [6.8667, 81.0466],
      [6.9934, 81.0550],
    ],
    rating: 4.7,
    reviews: 530,
    isInternal: false,
  },
  {
    name: "Galle / Matara ↔ Bandarawela Expressway Express",
    routeNumber: "Route 31/EX",
    origin: "Galle Central / Matara",
    destination: "Bandarawela Bus Stop",
    via: "Southern Expressway (E01) → Godagama → Hambantota → Wellawaya → Bandarawela",
    busTimes: [
      { time: "06:15 AM", tag: "Coast-to-Hills Morning", icon: "🏖️" },
      { time: "09:45 AM", tag: "Highway Express", icon: "⚡" },
      { time: "01:15 PM", tag: "Southern Line", icon: "🚌" },
      { time: "05:00 PM", tag: "Evening Express", icon: "🌇" },
    ],
    phone: "+94 91 223 4235",
    conductorPhone: "+94 41 222 2235",
    hotline: "+94 91 223 4235 (Galle SLTB)",
    fare: "LKR 1,950",
    busType: "AC Highway Luxury Coach",
    description: "Fast coastal to mountain express bus connecting Southern Province beaches directly to Uva hills.",
    image: "/images/Nearby facilities/Galle Bandarawela Highway Bus.jpg",
    position: [6.82977, 80.98457],
    routeWaypoints: [
      [6.0535, 80.2210],
      [5.9496, 80.5469],
      [6.1241, 81.1185],
      [6.7410, 81.1010],
      [6.82977, 80.98457],
    ],
    rating: 4.8,
    reviews: 310,
    isInternal: false,
  },
  {
    name: "Monaragala ↔ Colombo Highway Express",
    routeNumber: "Route 98/EX",
    origin: "Monaragala Central",
    destination: "Colombo Pettah",
    via: "Wellawaya → Beragala → Balangoda → Ratnapura → Kottawa Interchange",
    busTimes: [
      { time: "04:00 AM", tag: "Early Bird Express", icon: "🌅" },
      { time: "07:15 AM", tag: "Interchange Express", icon: "🚌" },
      { time: "11:30 AM", tag: "Midday Coach", icon: "☀️" },
      { time: "03:45 PM", tag: "Express Line", icon: "⚡" },
      { time: "10:00 PM", tag: "Night Sleeper", icon: "🌙" },
    ],
    phone: "+94 55 227 6235",
    conductorPhone: "+94 77 911 1161",
    hotline: "1955 (NTC Information)",
    fare: "LKR 1,650",
    busType: "AC Semi-Luxury Express Coach",
    description: "Long distance express bus connecting Monaragala district to Colombo capital city.",
    image: "/images/Nearby facilities/Monaragala Colombo Bus.jpg",
    position: [6.8732, 81.3508],
    routeWaypoints: [
      [6.8732, 81.3508],
      [6.7410, 81.1010],
      [6.6828, 80.3992],
      [6.9271, 79.8612],
    ],
    rating: 4.5,
    reviews: 280,
    isInternal: false,
  },
  {
    name: "Bandarawela ↔ Ella ↔ Wellawaya Local Shuttle",
    routeNumber: "Route 311 / Local",
    origin: "Bandarawela Bus Station",
    destination: "Wellawaya Central",
    via: "Kumbalwela → Ella Town → Ravana Ella Waterfall → Wellawaya",
    busTimes: [
      { time: "06:00 AM", tag: "First Morning Shuttle", icon: "🌅" },
      { time: "07:30 AM", tag: "School & Office Shuttle", icon: "🚌" },
      { time: "09:15 AM", tag: "Tourist Scenic Local", icon: "⛰️" },
      { time: "11:45 AM", tag: "Midday Loop", icon: "☀️" },
      { time: "02:30 PM", tag: "Afternoon Shuttle", icon: "🚍" },
      { time: "05:15 PM", tag: "Evening Commuter", icon: "🌆" },
      { time: "07:45 PM", tag: "Last Night Shuttle", icon: "🌙" },
    ],
    phone: "+94 57 222 2281",
    conductorPhone: "+94 77 105 7740",
    hotline: "+94 57 222 2281 (Bandarawela Depot)",
    fare: "LKR 180",
    busType: "SLTB / Private Normal Local Bus (Every 20 mins)",
    description: "High-frequency local Uva shuttle connecting Bandarawela town center, Ella tourist strip, and Ravana Falls.",
    image: "/images/Nearby facilities/Colombo Ella Express Bus.jpg",
    position: [6.8667, 81.0466],
    routeWaypoints: [
      [6.82977, 80.98457],
      [6.8667, 81.0466],
      [6.8410, 81.0540],
      [6.7410, 81.1010],
    ],
    rating: 4.7,
    reviews: 340,
    isInternal: true,
  },
  {
    name: "Bandarawela ↔ Diyatalawa ↔ Haputale Local Line",
    routeNumber: "Route 314 / Local",
    origin: "Bandarawela Central",
    destination: "Haputale Town & Station",
    via: "Kinigama → Diyatalawa Garrison Town → Kahagolla → Haputale",
    busTimes: [
      { time: "06:15 AM", tag: "Morning Garrison Shuttle", icon: "🎖️" },
      { time: "08:00 AM", tag: "School & Local Pass", icon: "🚌" },
      { time: "10:30 AM", tag: "Adisham Monastery Local", icon: "⛪" },
      { time: "01:15 PM", tag: "Afternoon Shuttle", icon: "☀️" },
      { time: "04:00 PM", tag: "Diyatalawa Commuter", icon: "🌆" },
      { time: "06:45 PM", tag: "Night Local", icon: "🌙" },
    ],
    phone: "+94 57 222 2281",
    conductorPhone: "+94 71 546 1710",
    hotline: "+94 57 222 2281 (Bandarawela SLTB)",
    fare: "LKR 140",
    busType: "SLTB Garrison & Mountain Local Line",
    description: "Convenient local bus connecting Bandarawela, Diyatalawa garrison town, and Haputale hill station.",
    image: "/images/Nearby facilities/Orient Hotel Bandarawela.jpg",
    position: [6.7722, 80.9309],
    routeWaypoints: [
      [6.82977, 80.98457],
      [6.8120, 80.9580],
      [6.7722, 80.9309],
    ],
    rating: 4.6,
    reviews: 290,
    isInternal: true,
  },
  {
    name: "Badulla ↔ Bandarawela Local Commuter",
    routeNumber: "Route 310 / Local",
    origin: "Badulla Bus Stand",
    destination: "Bandarawela Central",
    via: "Hali-Ela → Demodara Loop → Kumbalwela → Bandarawela",
    busTimes: [
      { time: "05:45 AM", tag: "Early Commuter", icon: "🌅" },
      { time: "07:15 AM", tag: "Peak Morning Shuttle", icon: "⚡" },
      { time: "09:30 AM", tag: "High-Frequency Local", icon: "🚌" },
      { time: "12:00 PM", tag: "Midday Pass", icon: "☀️" },
      { time: "03:15 PM", tag: "Afternoon Express", icon: "🌆" },
      { time: "06:30 PM", tag: "Evening Commuter", icon: "🌙" },
    ],
    phone: "+94 55 222 2235",
    conductorPhone: "+94 76 590 0100",
    hotline: "+94 55 222 2235 (Badulla Depot)",
    fare: "LKR 160",
    busType: "High-Frequency Local Commuter (Every 15 mins)",
    description: "Main arterial local bus connecting Uva District Capital Badulla to Bandarawela via Hali-Ela and Demodara.",
    image: "/images/Nearby facilities/Colombo Badulla Intercity Bus.jpg",
    position: [6.9934, 81.0550],
    routeWaypoints: [
      [6.9934, 81.0550],
      [6.9500, 81.0300],
      [6.884151, 81.059279],
      [6.82977, 80.98457],
    ],
    rating: 4.8,
    reviews: 410,
    isInternal: true,
  },
  {
    name: "Bandarawela ↔ Welimada ↔ Hakgala Local Pass",
    routeNumber: "Route 315 / Local",
    origin: "Bandarawela Bus Stop",
    destination: "Welimada & Hakgala Gardens",
    via: "Boralanda → Welimada Town → Keppetipola → Hakgala Border",
    busTimes: [
      { time: "06:30 AM", tag: "Morning Mountain Pass", icon: "🌅" },
      { time: "08:45 AM", tag: "Welimada Market Bus", icon: "🥦" },
      { time: "11:15 AM", tag: "Botanical Local", icon: "🌺" },
      { time: "02:00 PM", tag: "Afternoon Shuttle", icon: "☀️" },
      { time: "05:00 PM", tag: "Evening Return", icon: "🌆" },
    ],
    phone: "+94 57 224 5235",
    conductorPhone: "+94 77 105 7740",
    hotline: "+94 57 224 5235 (Welimada SLTB)",
    fare: "LKR 190",
    busType: "SLTB Mountain Valley Local Bus",
    description: "Scenic valley bus connecting Bandarawela, Welimada vegetable region, and Hakgala Botanical Gardens border.",
    image: "/images/Nearby facilities/Kandy Badulla Intercity Bus.jpg",
    position: [6.9015, 80.9520],
    routeWaypoints: [
      [6.82977, 80.98457],
      [6.9015, 80.9520],
      [6.9497, 80.7891],
    ],
    rating: 4.5,
    reviews: 210,
    isInternal: true,
  },
];

const Facility = require("./models/Facility");

const facilitiesData = [
  { name: "Bandarawela Heritage Hotel", type: "Hotel", location: "Central Bandarawela", description: "Colonial-style heritage hotel in central Bandarawela town.", phone: "+94 57 222 2501", rating: 4.5, reviews: 512, image: "/images/Nearby facilities/Bandarawela Heritage Hotel.jpg", lat: 6.8315, lng: 80.9880, openingDays: "Monday - Sunday", openingHours: "24 Hours Check-in", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Bandarawela+Heritage+Hotel" },
  { name: "Orient Hotel Bandarawela", type: "Hotel", location: "Bandarawela Town", description: "City hotel close to Bandarawela bus stand.", phone: "+94 57 222 2407", rating: 4.3, reviews: 380, image: "/images/Nearby facilities/Orient Hotel Bandarawela.jpg", lat: 6.8285, lng: 80.9850, openingDays: "Monday - Sunday", openingHours: "24 Hours Check-in", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Orient+Hotel+Bandarawela" },
  { name: "Melheim Resort & Spa", type: "Hotel", location: "Haputale Hillside", description: "Luxury hillside resort overlooking southern plains from Haputale.", phone: "+94 57 226 8000", rating: 4.7, reviews: 840, image: "/images/Nearby facilities/Melheim Resort & Spa.jpg", lat: 6.7680, lng: 80.9420, openingDays: "Monday - Sunday", openingHours: "24 Hours Check-in", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Melheim+Resort+%26+Spa+Haputale" },
  { name: "Olympus Plaza Hotel", type: "Hotel", location: "Haputale Station Rd", description: "Scenic hotel located near Haputale railway station.", phone: "+94 57 226 8200", rating: 4.2, reviews: 410, image: "/images/Nearby facilities/Olympus Plaza Hotel.jpg", lat: 6.7685, lng: 80.9580, openingDays: "Monday - Sunday", openingHours: "24 Hours Check-in", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Olympus+Plaza+Hotel+Haputale" },
  { name: "Diyatalawa Heritage Bungalow", type: "Hotel", location: "Diyatalawa", description: "Charming bungalow in the cool climate of Diyatalawa.", phone: "+94 57 222 9100", rating: 4.6, reviews: 215, image: "/images/Nearby facilities/Diyatalawa Heritage Bungalow.jpg", lat: 6.8120, lng: 80.9580, openingDays: "Monday - Sunday", openingHours: "24 Hours Check-in", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Diyatalawa+Heritage+Bungalow" },
  { name: "EKHO Ella", type: "Hotel", location: "Central Ella Town", description: "Hotel accommodation in central Ella town.", phone: "+94 57 222 8655", rating: 4.6, reviews: 656, image: "/images/Nearby facilities/EKHO Ella.jpg", lat: 6.8710, lng: 81.0490, openingDays: "Monday - Sunday", openingHours: "24 Hours Check-in", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=EKHO+Ella" },
  { name: "Morning Dew Hotel", type: "Hotel", location: "Ella Gap", description: "Comfortable accommodation with easy access to Ella attractions.", phone: "+94 57 493 3373", rating: 4.3, reviews: 632, image: "/images/Nearby facilities/Morning Dew Hotel.jpg", lat: 6.8725, lng: 81.0475, openingDays: "Monday - Sunday", openingHours: "24 Hours Check-in", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Morning+Dew+Hotel+Ella" },

  { name: "Bandarawela Rest House Dining", type: "Restaurant", location: "Bandarawela", description: "Traditional Sri Lankan and Western dining in historic Bandarawela.", phone: "+94 57 222 2201", rating: 4.4, reviews: 420, image: "/images/Nearby facilities/Bandarawela Rest House Dining.jpg", lat: 6.8305, lng: 80.9865, openingDays: "Monday - Sunday", openingHours: "07:00 AM - 10:00 PM", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Bandarawela+Rest+House" },
  { name: "Welimada Family Restaurant", type: "Restaurant", location: "Welimada", description: "Spacious restaurant serving hill country cuisine in Welimada.", phone: "+94 57 224 5100", rating: 4.2, reviews: 290, image: "/images/Nearby facilities/Welimada Family Restaurant.jpg", lat: 6.9020, lng: 80.9160, openingDays: "Monday - Sunday", openingHours: "07:30 AM - 09:30 PM", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Welimada+Family+Restaurant" },
  { name: "Misty Mountain Cafe Haputale", type: "Restaurant", location: "Haputale Viewpoint", description: "Popular local cafe overlooking the Haputale mist gap.", phone: "+94 57 226 8110", rating: 4.5, reviews: 580, image: "/images/Nearby facilities/Misty Mountain Cafe Haputale.jpg", lat: 6.7682, lng: 80.9570, openingDays: "Monday - Sunday", openingHours: "07:00 AM - 09:00 PM", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Misty+Mountain+Cafe+Haputale" },
  { name: "Risara Bakers & Restaurant", type: "Restaurant", location: "Haputale Town", description: "Fresh pastries, short eats, and tea in Haputale.", phone: "+94 57 226 8050", rating: 4.3, reviews: 310, image: "/images/Nearby facilities/Risara Bakers & Restaurant.jpg", lat: 6.7675, lng: 80.9565, openingDays: "Monday - Sunday", openingHours: "06:00 AM - 09:00 PM", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Risara+Bakers+Haputale" },
  { name: "360 Ella", type: "Restaurant", location: "Ella Main Street", description: "Popular main street restaurant in Ella.", phone: "+94 76 288 7480", rating: 4.6, reviews: 6361, image: "/images/Nearby facilities/360 Ella.jpg", lat: 6.8712, lng: 81.0488, openingDays: "Monday - Sunday", openingHours: "08:00 AM - 11:00 PM", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=360+Ella" },
  { name: "Cafe Chill", type: "Restaurant", location: "Ella Main Street", description: "Vibrant cafe and lounge in Ella.", phone: "+94 77 180 4020", rating: 4.5, reviews: 12184, image: "/images/Nearby facilities/Cafe Chill.jpg", lat: 6.8708, lng: 81.0492, openingDays: "Monday - Sunday", openingHours: "08:00 AM - 11:30 PM", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Cafe+Chill+Ella" },

  { name: "Ceypetco Central Station Bandarawela", type: "Fuel Station", location: "Bandarawela Town", description: "24/7 filling station serving petrol and diesel in Bandarawela.", phone: "+94 57 222 2234", rating: 4.4, reviews: 512, image: "/images/Nearby facilities/Ceypetco Central Station Bandarawela.jpg", lat: 6.8320, lng: 80.9860, openingDays: "Monday - Sunday", openingHours: "Open 24 Hours", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Ceypetco+Bandarawela" },
  { name: "LIOC Fuel Station Bandarawela", type: "Fuel Station", location: "Badulla Road, Bandarawela", description: "Lanka IOC station located on Badulla road.", phone: "+94 57 222 2890", rating: 4.3, reviews: 320, image: "/images/Nearby facilities/LIOC Fuel Station Bandarawela.jpg", lat: 6.8340, lng: 80.9910, openingDays: "Monday - Sunday", openingHours: "06:00 AM - 10:00 PM", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=LIOC+Fuel+Station+Bandarawela" },
  { name: "Ceypetco Filling Station Haputale", type: "Fuel Station", location: "Haputale Town", description: "Main fuel station serving travellers in Haputale.", phone: "+94 57 226 8020", rating: 4.2, reviews: 210, image: "/images/Nearby facilities/Ceypetco Filling Station Haputale.jpg", lat: 6.7670, lng: 80.9560, openingDays: "Monday - Sunday", openingHours: "06:00 AM - 09:00 PM", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Ceypetco+Haputale" },
  { name: "Diyatalawa Fuel Station", type: "Fuel Station", location: "Diyatalawa Garrison Town", description: "Fuel station in Diyatalawa military town.", phone: "+94 57 222 9050", rating: 4.3, reviews: 180, image: "/images/Nearby facilities/Diyatalawa Fuel Station.jpg", lat: 6.8140, lng: 80.9610, openingDays: "Monday - Sunday", openingHours: "06:00 AM - 09:30 PM", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Diyatalawa+Fuel+Station" },

  { name: "Bandarawela District Base Hospital", type: "Medical", location: "Bandarawela Town", description: "Primary district hospital in Bandarawela with 24h emergency room.", phone: "+94 57 222 2261", rating: 4.5, reviews: 430, image: "/images/Nearby facilities/Bandarawela District Base Hospital.jpg", lat: 6.8335, lng: 80.9890, openingDays: "Monday - Sunday", openingHours: "Open 24 Hours (ER)", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Bandarawela+District+Base+Hospital" },
  { name: "Haputale Base Hospital", type: "Medical", location: "Haputale Town", description: "Government hospital providing medical care in Haputale.", phone: "+94 57 226 8061", rating: 4.3, reviews: 190, image: "/images/Nearby facilities/Haputale Base Hospital.jpg", lat: 6.7690, lng: 80.9590, openingDays: "Monday - Sunday", openingHours: "Open 24 Hours (ER)", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Haputale+Base+Hospital" },

  { name: "Bandarawela Division Police Station", type: "Police", location: "Bandarawela HQ", description: "Headquarters police station in Bandarawela.", phone: "+94 57 222 2222", rating: 4.4, reviews: 180, image: "/images/Nearby facilities/Bandarawela Division Police Station.jpg", lat: 6.8310, lng: 80.9855, openingDays: "Monday - Sunday", openingHours: "Open 24 Hours", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Bandarawela+Police+Station" },
  { name: "Ella Police Station", type: "Police", location: "Ella Main Rd", description: "Local police station serving the Ella area.", phone: "+94 57 222 8522", rating: 4.2, reviews: 115, image: "/images/Nearby facilities/Ella Police Station.jpg", lat: 6.8735, lng: 81.0472, openingDays: "Monday - Sunday", openingHours: "Open 24 Hours", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Ella+Police+Station" },

  { name: "Scan Alpine Camping Store", type: "Camping", location: "Ella Town", description: "Camping and outdoor equipment store in Ella.", phone: "+94 57 223 5107", rating: 4.7, reviews: 60, image: "/images/Nearby facilities/Scan Alpine Camping Store.jpg", lat: 6.8720, lng: 81.0480, openingDays: "Monday - Saturday", openingHours: "08:30 AM - 07:00 PM", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Scan+Alpine+Camping+Ella" },
  { name: "Ella Scooter Rental EllaBike", type: "Bike Rental", location: "Ella Station Rd", description: "Scooter rental service for exploring Ella and surrounding areas.", phone: "+94 77 911 1161", rating: 4.8, reviews: 248, image: "/images/Nearby facilities/Ella Scooter Rental EllaBike.jpg", lat: 6.8700, lng: 81.0490, openingDays: "Monday - Sunday", openingHours: "08:00 AM - 08:00 PM", googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=Ella+Scooter+Rental+EllaBike" },
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);

    console.log("MongoDB connected");

    await Place.deleteMany();
    await Place.insertMany(places);
    console.log("10 places inserted successfully!");

    await BusService.deleteMany();
    await BusService.insertMany(busServicesData);
    console.log("10 bus services inserted successfully!");

    await Facility.deleteMany();
    await Facility.insertMany(facilitiesData);
    console.log("Facilities inserted successfully!");

    await mongoose.connection.close();
    process.exit(0);
  } catch (error) {
    console.error("Seeding failed:");
    console.error(error.message);

    process.exit(1);
  }
};

seedDatabase();